// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNbosVq3DqW0tKtnkxWwVDnSpffhHbJQ',
    appId: '1:174960454604:web:38f20b785520ce09538b69',
    messagingSenderId: '174960454604',
    projectId: 'cobit-dss-app',
    authDomain: 'cobit-dss-app.firebaseapp.com',
    storageBucket: 'cobit-dss-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLykifgUNxMGFgGUYbccLJvc7_DaCUGE',
    appId: '1:174960454604:android:bba540d6b92bbae2538b69',
    messagingSenderId: '174960454604',
    projectId: 'cobit-dss-app',
    storageBucket: 'cobit-dss-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjetsX-dHx8q6k9Mu7moh6722rk5boqo',
    appId: '1:174960454604:ios:2a78e8a87a6fc9b6538b69',
    messagingSenderId: '174960454604',
    projectId: 'cobit-dss-app',
    storageBucket: 'cobit-dss-app.appspot.com',
    iosClientId:
        '174960454604-bd0rtdo8529gao61setltggbk7hc1771.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobitDssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjetsX-dHx8q6k9Mu7moh6722rk5boqo',
    appId: '1:174960454604:ios:32041a3d0ee272f3538b69',
    messagingSenderId: '174960454604',
    projectId: 'cobit-dss-app',
    storageBucket: 'cobit-dss-app.appspot.com',
    iosClientId:
        '174960454604-biubfjavuvf2dahmf3r4ssuss8svsbvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobitDssApp.RunnerTests',
  );
}
